name: Java_CI_with_Maven
#
on: [push]

jobs:
  build:
    name: build-job
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file flyway-test-extensions/pom.xml
